### ISSUE TITLE
What's the reason why the panel doesn't display AkSkPane?

### ISSUE THREAD

**Issue by Xiaosesh** [libaibaia/BucketVulTools#2]
After downloading and importing the distribution extension of BucketVulTool-1.0.jar here, the panel does not report any errors. Why does it not display AkSkPane? Cannot be used, latest version.

**Comment by libaibaia** [comment]
> After downloading and importing the distribution extension of BucketVulTool-1.0.jar here, the panel does not report any errors. Why does it not display AkSkPane? Cannot be used, latest version.

If you want to open AKSKPane, you can remove the following code comments and you'll see AKSKPane when you import bp after repacking
![image](https://github.com/user-attachments/assets/96904770-5e85-4016-be0b-57cccc3332e2)
![image](https://github.com/user-attachments/assets/c6ed1486-1ff2-437e-867f-f7c3e3689814)

**Comment by libaibaia** [comment]
> After downloading and importing the distribution extension of BucketVulTool-1.0.jar here, the panel does not report any errors. Why does it not display AkSkPane? Cannot be used, latest version.

The shutdown is due to wasted performance and a high false positive rate. If you only want to detect sensitive information, you can refer to the HAE plug-in

**Comment by Xiaosesh** [comment]
> > After downloading and importing the distribution extension of BucketVulTool-1.0.jar here, the panel does not report any errors. Why does it not display AkSkPane? Cannot be used, latest version.
> 
> The shutdown is due to wasted performance and a high false positive rate. If you only want to detect sensitive information, you can refer to the HAE plug-in

Since that's the case, how can I confirm that BucketVulTools (the plugin) has detected improper configuration of the bucket?

**Comment by libaibaia** [comment]
> > > After downloading and importing the distribution extension of BucketVulTool-1.0.jar here, the panel does not report any errors. Why does it not display AkSkPane? Cannot be used, latest version.
> > 
> > 
> > The shutdown is due to wasted performance and a high false positive rate. If you only want to detect sensitive information, you can refer to the HAE plug-in
> 
> Since that's the case, how can I confirm that BucketVulTools (the plugin) has detected improper configuration of the bucket?

You can refer to the introduction on the homepage, these are two security issues, and sensitive information detection is only an option. The main function of BucketVulTools is to detect bucket vulnerabilities, and if bucket-related vulnerabilities are detected, they can be seen from the Burpsuite issue page, such as ACLs

**Comment by DamnVanish** [comment]
我觉得可以发行一个可以看到检测出来漏洞也就是有面板的版本😂有面板还是简洁点

**Comment by libaibaia** [comment]
> 我觉得可以发行一个可以看到检测出来漏洞也就是有面板的版本😂有面板还是简洁点
可以，过几天加一个

**Comment by libaibaia** [comment]
已更新添加支持，https://github.com/libaibaia/BucketVulTools/commit/bbc14436b9de4bb832a79c407da9cb5e61f21d2d
